

# -*- coding: utf-8 -*-
"""AIAgentdemo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKOcUY-_SckHcb6aCYqd_JK5hbYooPfv
"""

from crewai import Agent, Task, Crew, Process
from crewai_tools import SerperDevTool

search_tool = SerperDevTool()

from langchain_openai import ChatOpenAI

researcher = Agent(
    role = "Senior Research Assistant",
    goal = "Look up the latest trending website designs",
    backstory = """You work at a leading tech company.
    Your expertise lies in searcing Google for web design concepts.
    You have a knack for dissecting complex data and presenting actionable insights.""",
    verbose=True,
    allow_delegation=False,
    tool=[search_tool],
    llm= ChatOpenAI(model_name="gpt-3.5-turbo-0125", temperature=0.2)
)

designer = Agent(
    role = "Senior UX/UI designer",
    goal = "Design the looks and experience of the website specified in the task",
    backstory = """You work at a leading tech company.
    Your expertise lies in designing beautiful user interfaces.
    You have a knack for combining research with your own ideas to create smooth experiences.""",
    verbose=True,
    allow_delegation=True,
    llm= ChatOpenAI(model_name="gpt-3.5-turbo-0125", temperature=0.8)
)

developer = Agent(
    role = "Senior Web Developer",
    goal = "Build the website with efficient and understandable code using HTML, CSS and Javascript",
    backstory = """You work at a leading tech company.
    Your expertise lies in building precisely the designs given to you.
    You have a knack for writing simple but efficient code.""",
    verbose=True,
    allow_delegation=True,
    llm= ChatOpenAI(model_name="gpt-3.5-turbo-0125", temperature=0.3)
)

task1 = Task(
    description="""Conduct a comprehensive analysis of the latest trends in web design for artists in July 2024.
    Identify new and brave ideas, new technologies, and potential industry impacts.""",
    expected_output="Full analysis report in bullet points",
    agent=researcher
)

task2 = Task(
    description="""Using the insights provided together with your own brilliant ideas, develop a set of 5 images that showcases your UX design.
     Include branding, identity and page layouts on mobile and desktop.""",
    expected_output="Website design images with branding identity",
    agent=designer
)

task3 = Task(
    description="""Using the design provided, build a functioning website using HTML, CSS and Javascript.
     Add comments for clarity, and test the code for bugs. Take care about responsiveness over mobile and desktop.""",
    expected_output="two files: index.html, styles.css",
    agent=developer
)

crew = Crew(
    agents= [researcher, designer, developer],
    tasks= [task1, task2, task3],
    verbose = 1,
)

result = crew.kickoff()
print("#########################-############################")
print(result)